name: vector_tile
version: 0.3.1
description: >-
  A simple Dart package to encode & decode Mapbox Vector Tile, A implementation of Mapbox Vector Tile specification.
homepage: https://github.com/saigontek/dart-vector-tile
documentation: https://github.com/saigontek/dart-vector-tile
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  fixnum: ^1.0.0
  protobuf: ^2.0.0
dev_dependencies:
  pedantic: ^1.9.2
