name: vector_tile
version: 0.0.1
description: >-
  A Dart package to encode & decode Mapbox Vector Tile, it refers to a specification developed by MapBox (https://github.com/mapbox/vector-tile-spec).
homepage: https://example-pet-store.com/newtify
documentation: https://example-pet-store.com/newtify/docs
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  meta: ^1.2.4
  fixnum: ^0.10.9
  protobuf: '>=1.1.0 <2.0.0'
#   efts: ^2.0.4
#   transmogrify: ^0.4.0
# dev_dependencies:
#   test: '>=1.15.0 <2.0.0'