name: vector_tile
version: 0.0.2
description: >-
  A simple Dart package to encode & decode Mapbox Vector Tile, it refers to a specification developed by MapBox (https://github.com/mapbox/vector-tile-spec).
homepage: https://github.com/saigontek/dart-vector-tile
documentation: https://github.com/saigontek/dart-vector-tile
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  meta: ^1.2.4
  fixnum: ^0.10.9
  protobuf: '>=1.1.0 <2.0.0'